import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

SizedBox gv05 = SizedBox(height: 05.h);
SizedBox gv10 = SizedBox(height: 10.h);
SizedBox gv15 = SizedBox(height: 15.h);
SizedBox gv20 = SizedBox(height: 20.h);
SizedBox gv25 = SizedBox(height: 25.h);
SizedBox gv30 = SizedBox(height: 30.h);
SizedBox gv35 = SizedBox(height: 35.h);
SizedBox gv40 = SizedBox(height: 40.h);
SizedBox gv45 = SizedBox(height: 45.h);
SizedBox gv50 = SizedBox(height: 50.h);
SizedBox gv55 = SizedBox(height: 55.h);
SizedBox gv60 = SizedBox(height: 60.h);
SizedBox gv65 = SizedBox(height: 65.h);
SizedBox gv70 = SizedBox(height: 70.h);
SizedBox gv75 = SizedBox(height: 75.h);
SizedBox gv80 = SizedBox(height: 80.h);
SizedBox gv85 = SizedBox(height: 85.h);
SizedBox gv90 = SizedBox(height: 90.h);
SizedBox gv95 = SizedBox(height: 95.h);
SizedBox gv100 = SizedBox(height: 100.h);

SizedBox gh05 = SizedBox(width: 05.w);
SizedBox gh10 = SizedBox(width: 10.w);
SizedBox gh15 = SizedBox(width: 15.w);
SizedBox gh20 = SizedBox(width: 20.w);
SizedBox gh25 = SizedBox(width: 25.w);
SizedBox gh30 = SizedBox(width: 30.w);
SizedBox gh35 = SizedBox(width: 35.w);
SizedBox gh40 = SizedBox(width: 40.w);
SizedBox gh45 = SizedBox(width: 45.w);
SizedBox gh50 = SizedBox(width: 50.w);
SizedBox gh55 = SizedBox(width: 55.w);
SizedBox gh60 = SizedBox(width: 60.w);
SizedBox gh65 = SizedBox(width: 65.w);
SizedBox gh70 = SizedBox(width: 70.w);
SizedBox gh75 = SizedBox(width: 75.w);
SizedBox gh80 = SizedBox(width: 80.w);
SizedBox gh85 = SizedBox(width: 85.w);
SizedBox gh90 = SizedBox(width: 90.w);
SizedBox gh95 = SizedBox(width: 95.w);
SizedBox gh100 = SizedBox(width: 100.w);
